name:                app
version:             0.1.0.0
github:              "ryu1kn/sandbox--scotty"
license:             MIT
author:              "Ryuichi Inagaki"
maintainer:          "example@example.com"
copyright:           "2020 Ryuichi Inagaki"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ryu1kn/sandbox--scotty#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  app:
    main:                Main.hs
    source-dirs:         .
    other-extensions:    OverloadedStrings
    other-modules:
    - Client.CSS
    - Controllers.Home
    - Views.Home
    - Views.Utils
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-extra
    - wai-middleware-static
    - scotty
    - clay
    - text
    - blaze-html
    - blaze-markup
    - aeson
